// <auto-generated />
using System;
using AuthService.Persistence.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AuthService.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AuthService.Domain.Entities.Role", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_role");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_role_name");

                    b.ToTable("role", (string)null);
                });

            modelBuilder.Entity("AuthService.Domain.Entities.Administrator", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)")
                        .HasColumnName("name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password");

                    b.Property<bool>("Status")
                        .HasColumnType("boolean")
                        .HasColumnName("status");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("surname");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Administratorname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("administratorname");

                    b.HasKey("Id")
                        .HasName("pk_administrator");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_administrator_email");

                    b.HasIndex("Administratorname")
                        .IsUnique()
                        .HasDatabaseName("ix_administrator_administratorname");

                    b.ToTable("administrator", (string)null);
                });

            modelBuilder.Entity("AuthService.Domain.Entities.AdministratorEmail", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("id");

                    b.Property<string>("EmailVerificationToken")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email_verification_token");

                    b.Property<DateTime?>("EmailVerificationTokenExpiry")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("email_verification_token_expiry");

                    b.Property<bool>("EmailVerified")
                        .HasColumnType("boolean")
                        .HasColumnName("email_verified");

                    b.Property<string>("AdministratorId")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("administrator_id");

                    b.HasKey("Id")
                        .HasName("pk_administrator_email");

                    b.HasIndex("AdministratorId")
                        .IsUnique()
                        .HasDatabaseName("ix_administrator_email_administrator_id");

                    b.ToTable("administrator_email", (string)null);
                });

            modelBuilder.Entity("AuthService.Domain.Entities.AdministratorPasswordReset", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("id");

                    b.Property<string>("PasswordResetToken")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("password_reset_token");

                    b.Property<DateTime?>("PasswordResetTokenExpiry")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("password_reset_token_expiry");

                    b.Property<string>("AdministratorId")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("administrator_id");

                    b.HasKey("Id")
                        .HasName("pk_administrator_password_reset");

                    b.HasIndex("AdministratorId")
                        .IsUnique()
                        .HasDatabaseName("ix_administrator_password_reset_administrator_id");

                    b.ToTable("administrator_password_reset", (string)null);
                });

            modelBuilder.Entity("AuthService.Domain.Entities.AdministratorProfile", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("id");

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("bio");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_of_birth");

                    b.Property<string>("ProfilePictureUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("profile_picture_url");

                    b.Property<string>("AdministratorId")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("administrator_id");

                    b.HasKey("Id")
                        .HasName("pk_administrator_profile");

                    b.HasIndex("AdministratorId")
                        .IsUnique()
                        .HasDatabaseName("ix_administrator_profile_administrator_id");

                    b.ToTable("administrator_profile", (string)null);
                });

            modelBuilder.Entity("AuthService.Domain.Entities.AdministratorRole", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("id");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("assigned_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("role_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("AdministratorId")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("administrator_id");

                    b.HasKey("Id")
                        .HasName("pk_administrator_role");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_administrator_role_role_id");

                    b.HasIndex("AdministratorId", "RoleId")
                        .IsUnique()
                        .HasDatabaseName("ix_administrator_role_administrator_id_role_id");

                    b.ToTable("administrator_role", (string)null);
                });

            modelBuilder.Entity("AuthService.Domain.Entities.AdministratorEmail", b =>
                {
                    b.HasOne("AuthService.Domain.Entities.Administrator", "Administrator")
                        .WithOne("AdministratorEmail")
                        .HasForeignKey("AuthService.Domain.Entities.AdministratorEmail", "AdministratorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_administrator_email_administrator_administrator_id");

                    b.Navigation("Administrator");
                });

            modelBuilder.Entity("AuthService.Domain.Entities.AdministratorPasswordReset", b =>
                {
                    b.HasOne("AuthService.Domain.Entities.Administrator", "Administrator")
                        .WithOne("AdministratorPasswordReset")
                        .HasForeignKey("AuthService.Domain.Entities.AdministratorPasswordReset", "AdministratorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_administrator_password_reset_administrator_administrator_id");

                    b.Navigation("Administrator");
                });

            modelBuilder.Entity("AuthService.Domain.Entities.AdministratorProfile", b =>
                {
                    b.HasOne("AuthService.Domain.Entities.Administrator", "Administrator")
                        .WithOne("AdministratorProfile")
                        .HasForeignKey("AuthService.Domain.Entities.AdministratorProfile", "AdministratorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_administrator_profile_administrator_administrator_id");

                    b.Navigation("Administrator");
                });

            modelBuilder.Entity("AuthService.Domain.Entities.AdministratorRole", b =>
                {
                    b.HasOne("AuthService.Domain.Entities.Role", "Role")
                        .WithMany("AdministratorRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_administrator_role_role_role_id");

                    b.HasOne("AuthService.Domain.Entities.Administrator", "Administrator")
                        .WithMany("AdministratorRoles")
                        .HasForeignKey("AdministratorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_administrator_role_administrator_administrator_id");

                    b.Navigation("Role");

                    b.Navigation("Administrator");
                });

            modelBuilder.Entity("AuthService.Domain.Entities.Role", b =>
                {
                    b.Navigation("AdministratorRoles");
                });

            modelBuilder.Entity("AuthService.Domain.Entities.Administrator", b =>
                {
                    b.Navigation("AdministratorEmail")
                        .IsRequired();

                    b.Navigation("AdministratorPasswordReset")
                        .IsRequired();

                    b.Navigation("AdministratorProfile")
                        .IsRequired();

                    b.Navigation("AdministratorRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
